version: '3.8' 
services: 
  Nginx_proxy: 
    image: nginx 
    build: 
      context: . 
      dockerfile: NginxDockerfile 
    ports: 
      - 8000:8000 
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks: 
      - web_network 
  Nginx_http1: 
    image: nginx 
    volumes: 
      - ./web1:/var/www/html 
    networks: 
      - web_network 
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;" 
  Nginx_http2: 
    image: nginx 
    volumes: 
      - ./web2:/var/www/html 
    networks: 
      - web_network 
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;" 
networks: 
  web_network: 
  driver: bridge